### ISSUE TITLE
Duplication image sur carte SD

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#1]
**Objectif :** faire marcher les 2 raspberry en dupliquant l'image sur la carte SD vierge.
Utiliser `etcher.io`

**Comment by micbuffa** [comment]
Aussi, passer à mon bureau récup une sd de 128 Go pour installer dessus : une distrib retropie vierge et apprendre à "faire une image" en ajoutant plein de roms, des "cores" (émulateurs) via les menus retropie etc...

**Comment by LoPastor** [comment]
retropie installée et configurée en suivant ce tutoriel : https://projetsdiy.fr/comment-installer-retropie-sur-raspbian-debuter-en-retrogaming-sur-raspberry-pi-3/ ; petit probleme pour me connecter sur le navigateur du retropie : mon ordinateur ne retrouve pas le raspBerry ; je continue mes recherches
