### ISSUE TITLE
Utiliser Scraper

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#10]
Utilisation de Scraper sous windows

**Comment by LoPastor** [comment]
Skraper utilisé et gamelist.xml obtenu.

Pour utiliser Skraper : 
- Connecter le raspberry au réseau
- Aller dans réseau, entrer \\'ipraspberry'
- Connecter à un réseau local les fichiers roms et configs
- Ouvrir Skraper
- Ouvrir les fichiers demandés
- Dans le menu, choisir la console pour laquelle vous voulez les images, etc...
- Aller dans l'onglet 'game et front-end' et lancer le skraper
- Une fois cela fait, récupérer la gamelist.xml dans le dossier associé (/roms/snes par exemple)

ATTENTION AVANT DE COMMENCER : BIEN VERiFIER LES CONFIGURATIONS RESEAUX DE VOTRE PC ET QUE LE SSH DU RASPBERRY SOIT 'ENABLE', CAR IL EST EN 'DISABLE' DE BASE.
