### ISSUE TITLE
Amélioration du serveur 

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#13]
Embellir le parcours de fichiers et répertoires sur le serveur

**Comment by DiopFatou** [comment]
J'ai travaillé sur la possibilité de pouvoir sélectionner le dossier dans lequel on veut charger un jeu ou un fichier. Pour l'instant, j'arrive à récupérer façon dynamique tous les dossiers du répertoires "roms" et à les afficher sur la page de chargement. Maintenant le problème que je rencontre, c'est de renvoyer le choix de l'utilisateur et le traiter côté serveur. Je continue dessus et une fois que ce sera fait on pourra automatiser l'utilisation du scraper pour générer le xml d'un jeu et le merger avec le gamelist.xml

![image](https://user-images.githubusercontent.com/32192151/54010859-c3e1ab80-4170-11e9-88b4-f29d29876444.png)
![image](https://user-images.githubusercontent.com/32192151/54010879-d825a880-4170-11e9-9c22-20e1562efef0.png)

**Comment by micbuffa** [comment]
Faudrait en discuter... je suis pas sur qu'un menu déroulant soit la
meilleure ergonomie.

Vous avez bien pris une approche "WebServices" comme on a fait en classe ?

**Comment by fs001848** [comment]
Nous allons faire des essais et nous verrons tous ensemble comment améliorer l'ergonomier et réfléchir à une maquette pour l'application web. Je ferme l'issue, une nouvelle sera créée détaillant ce que nous attendons pour la prochaine version.
