### ISSUE TITLE
Activer les trophés

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#17]

**Comment by LoPastor** [comment]
Trophées activées ; il faut juste créer un compte sur RetroAchievement http://retroachievements.org/
Ensuite rajouter ces 4 lignes dans le fichier /opt/retropie/configs/all/retroarch.cfg ; c'est en lignes de commandes, mais vous pouvez ouvrir sans problème avec Visual Studio Code.

cheevos_username = "RandomDude" //le nom de mon compte
cheevos_password = "haiPEPITO06" //mon mot de passe
cheevos_enable = true // permet d'activer les trophées
cheevos_verbose_enable = true //permet d'avoir un suivi des trophées gagnées

Vouz pouvez garder un aperçu des trophées gagnées sur le site RetroAchievement.

Tout est expliqué là-dedans :
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroAchievements

**Comment by fs001848** [comment]
Super merci !
