### ISSUE TITLE
Installer Skraper

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#3]
- Installer Skrapper [http://skraper.net/](http://skraper.net/)
- Rechercher la `gamelist.xml` pour la rom choisie

**Comment by LoPastor** [comment]
Skraper installé sur mon oridnateur mais je n'arrive pas à accéder à ses services : il me demande de choisir un Front-End, j'ai téléchargé et testé RecalBox et Retropie mais il ne reconnait aucun des deux
