### ISSUE TITLE
Améliorer web (recherche)

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#38]
- ajouter une zone de recherche
- trier les jeux par console (afficher uniquement les jeux d'une console)

**Comment by LoPastor** [comment]
ajouter plusieurs champs de recherche (console, type de jeu, éditeur, nom, date de sortie, (note moyenne?))

**Comment by fs001848** [comment]
Pour le moment on reste sur une recherche classique nom ou console je ferme l'issue et j'en ouvre une sur le nom du jeu uniquement
