### ISSUE TITLE
Merge des fichiers xml

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#4]
Merger manuellement les deux fichiers xml (celui qui contient tous les jeux du système de la rom et le nouveau créé par skraper.net)

**Comment by fs001848** [comment]
En attente de génération du fichier xml

**Comment by fs001848** [comment]
xml produit je donne les fichiers à Fatou pour qu'elle les ajoute sur le raspberry et qu'elle voit le résultat.

**Comment by DiopFatou** [comment]
Le contenu du fichier xml créé par Sylvain a pu être rajouté manuellement au gamelist.xml. Toutes les modifications apportées sont visible une fois EmulationStation redémarrée. Tout ce qui est images ou vidéos doivent être stockées dans le dossier "media"
