### ISSUE TITLE
Ajouter des éléments à la liste de jeux

### ISSUE THREAD

**Issue by LoPastor** [fs001848/projet-raspberry#45]
Rajouter comme champs du tableau l'éditeur, la date de sortie du jeu et le type de jeu (FPS, RPG, Aventure,...)

**Comment by LoPastor** [comment]
nous pouvons aussi envisager un champ "Multijoueur" qui aurait juste Oui ou Non comme valeurs, ou alors 1, 1-2, 1-4, etc... ; à voir

**Comment by fs001848** [comment]
changement. Vu comment est oraganisé notre JSON on reste comme ça pour le moment
