### ISSUE TITLE
Serveur - route JSON -

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#46]
pour récupérer la liste des jeux au format JSON :
```
{
    'infosJeux': [{
        'console': 'nes',
        'jeux': ['jeu1', 'jeu2', jeu3]
    }, {
        'console': 'amiga',
        'jeux': ['jeu1', 'jeu2', jeu3]    
    }]
}
```

**Comment by DiopFatou** [comment]
C'est fait comme on peut le voir sur la capture d'écran
![image](https://user-images.githubusercontent.com/32192151/56243521-1c269a00-609b-11e9-93b7-062ca7c2900f.png)
Il faudra juste supprimer les extensions dans la suite (.zip, .tzx...)
