### ISSUE TITLE
Installation et utilisation de Skyscraper

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#5]
Savoir utiliser Skyscraper sous MacOS / Linux.
[https://github.com/muldjord/skyscraper/](https://github.com/muldjord/skyscraper/)

**Comment by fs001848** [comment]
Skyscraper fonctionne mais rend un xml vide même avec le nom indentique au jeu sur Scraper. (nouvelle issue : trouver sur le forum). @paulinegld Arrives-tu à lancer la commande ?

**Comment by micbuffa** [comment]
Je vous avais passé une ligne de commande qui marchait bien. J'espère que vous suivez avec attention les posts de l'auteur sur le forum retropie.co.uk

Skyscraper --nolocaldb --refresh -p dreamcast --verbosity 3 -s screenscraper --videos --relative

Par exemple... mais çà suppose que vous avez configuré une fois la commande avec juste la commande Skyscraper. Et que vous posez les jeux dans un dossier roms/dreamcast qq part qui a été configuré. J'ai pris l'exemple de la dreamcast mais sinon changer le parametre -p 

Pour voir les cibles : Skyscraper -help et elles s'affichent...

Faudrait un peu avancer sur ce coup là... ça traine alors que découvrir comment lancer cette commande ça prend normalement 15mns pour un informaticien débrouillard... Oh, réveillez-vous !!!

**Comment by fs001848** [comment]
J'ai réussi à faire fonctionner Skyscraper sous linux et à produire le xml pour un jeu avec toutes les images. J'aimerais que Pauline et Fatou y arrivent aussi sous Mac. Je ferme cette issue.
