### ISSUE TITLE
Mettre en place un petit serveur

### ISSUE THREAD

**Issue by fs001848** [fs001848/projet-raspberry#8]
Faire fonctionner un petit serveur pour déposer un jeu sur le raspberry.

**Comment by micbuffa** [comment]
Et ?

**Comment by DiopFatou** [comment]
Un mini serveur est implémenté avec NodeJS. Le serveur est accessible à travers l'IP du raspberry, du port et de la route défini dans la config du serveur. Il permet actuellement de lister et parcourir les différents dossiers et fichiers du répertoire de base défini dans le serveur. Ex: 192.168.43.143:3000/file 

![image](https://user-images.githubusercontent.com/32192151/53523780-fa1e8b80-3add-11e9-9e86-b61553c4d799.png)
